---
# tasks file for docker-registry

- name: login
  docker_login:
    #email: "safta.yahya@esprit.tn"
    username: "yahya69"
    password: "3y8eg4JDZkbm4a6"
    reauthorize: yes
- name: docker push
  docker_image:
    name: appfront:latest
    repository: yahya69/repo
    push: yes
    source: local 
